services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=brian
      - POSTGRES_DB=portfolio_v3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
